@server=http://localhost:50398
@token=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJJZCI6IjEiLCJzdWIiOiIxIiwidW5pcXVlX25hbWUiOiJhZG1pbiIsImVtYWlsIjoibS56YXRraGFoaUBnbWFpbC5jb20iLCJqdGkiOiI1MzBlYWM4Zi1kMGE2LTQyOTgtYTI4OC1kMzUyNDYxYzNjNWEiLCJyb2xlIjoiQWRtaW5pc3RyYXRvciIsIm5iZiI6MTYzMjY4NTYwMCwiZXhwIjoxNjQwNDYxNjAwLCJpYXQiOjE2MzI2ODU2MDB9.4-b4U8AeeS5-HWSEa_P3R7XyjIRkmCCQXkBHTQWYkNXmr8Gx9FJTb7gm2J_Dy7kd4DBDrWQj7IW29ao4WMciTg


### register a new user
POST {{server}}/api/Account/create
Authorization: Bearer {{token}}
Content-Type: application/json

{
    firstName: "تست",
    lastName: "کاربر",
    userName: "test",
    email: "test@gmail.com",
    password: "123456",
    confirmPassword: "123456"    
}